### PR TITLE
better specificity for input[type=text]

### PR DESCRIPTION
**Pull request by todrobbins**
Didn't realize the body background was already white... Doh! This will actually adjust the input fields to be grey.

### CODE REVIEW

**Comment by smth** [comment]
I think the the inputs are better as they are, white with grey border. This way they can be visible on both a white and grey background.

**Comment by todrobbins** [comment]
I think what you describe would be sufficient as well, yet the site doesn't currently render inputs with grey borders:

screen shot 2015-03-18 at 10 15 03 am

This is why I was fiddling with background colors.

**Comment by smth** [comment]
Understood. That site is currently using a relatively old version of this theme however. It should be updated before too long, but if you want to see how things currently look I suggest getting a local version running.

**Comment by todrobbins** [comment]
Ah, gotcha. Are you the lead designer on the Omeka site? PS: Thanks for being understanding.

**Comment by smth** [comment]
I am indeed. No problem, I appreciate your input.

**Pull request closed without merging**
